config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :courses
  resources :students
  resources :sections
  resources :sessions

end

app/models/course.rb
class Course < ActiveRecord::Base
    has_many :sections, dependent: :destroy
    has_many :students, -> { distinct }, through: :sections
    validates :crn, presence: true, uniqueness: true
    
    #creates a new section for this course
    def add_section(num_sections = 0)
        num_sections.to_i.times do
            sections << Section.create
        end
    end
end

app/models/section.rb
class Section < ActiveRecord::Base
    belongs_to :course
    has_many :section_students, dependent: :destroy
    has_many :students, -> { distinct }, through: :section_students
    has_many :sessions
    
    
    #adds students to sections. this expects an array of student ids
    def add_students(student_ids)
        student_ids.each do |student_id|
            student = Student.find_by(id: student_id)
            students << student
        end
    end
    
    def remove_students(student_ids)
        student_ids.each do |student_id|
            student = Student.find_by(id: student_id)
            students.delete(student)
        end
    end
    
    # def add_student(student_id)
    #     student = Student.find_by(id: student_id)
    #     students << student
    # end
    
    # def remove_student(student_id)
    #     student = Student.find_by(id: student_id)
    #     students.delete(student)
    # end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
    
    
    def show
        @section = Section.find_by(id: params[:id])
        
    end
    
    def edit
        @section = Section.find_by(id: params[:id])
    end
    
    def update
        # add multiple students to the section
        @section = Section.find_by(id: params[:id])


        @section.add_students(not_enrolled)
        # @section.add_students(not_enrolled)
        @section.remove_students(enrolled)
        # flash['danger'] = not_enrolled
        # flash['danger'] = enrolled
        
        redirect_to edit_section_path(@section)
    end
    
    private
        def not_enrolled
            params.require(:section).permit(student_ids:[])["student_ids"] ||= []
        end
        def enrolled
            params.require(:section).permit(students:[])["students"] ||= []
        end
    
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/edit.html.erb
<% provide(:title, "Section detail") %>


<h1>Title: <%= "#{@section.course.crn} #{@section.course.title}"%></h1>
<%= link_to "Back to section view", section_path(@section), class: "btn btn-primary" %>


<%= form_for @section do |f|%>
    <% if @section.students.present? %>
        Remove students from section:
        <ul><% @section.students.each do |student| %>
            <!--this method will send the hidden field with '0', so make sure if unchecked, it returns nil instead of 0-->
            <li><%= f.check_box("students", {:multiple => true}, student.id, nil) %> <%=student.full_name%></li>
        
        <% end %>
        </ul>    
        <%end %>

    Add Students to section:
    <ul>
        <!--this method will send the hidden field with '0', so make sure if unchecked, it returns nil instead of 0-->
        
        <!--issue: i need top ass these multiple ids, but active record won't pass these ids through... because it is not a flattened array-->
        <!--need to get students who are not enrolled in any section of the course-->
        <!--need to reorder by id because default is order by first_name, and postgres has issue with ordering by a field that is not selected-->
        <% Student.where.not(id: @section.course.students.reorder(:id).ids).each do |student|%>
        <li><%= f.check_box("student_ids", {:multiple => true}, student.id, nil) %> <%= student.full_name%></li>
        <% end %>
    </ul>    
    
    <%= f.submit "Edit Students" %>
<% end %>

app/views/sections/show.html.erb
<% provide(:title, "Section detail") %>
<h1>Title: <%= "#{@section.course.crn} #{@section.course.title}"%></h1>
<h2>Section: <%= @section.id %></h2>
<%= link_to "Back to index", root_path, class: "btn btn-primary" %>


<h2>Attendance for <%= link_to "Today", new_session_path(section: @section, date: Date.today) %></h2>
<!--toggle the calendar if they want the do attendance for other days-->
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        
    <%= month_calendar partial: 'simple_calendar/calendar' do |date| %>
    <!--if there is no params, then it should be the current month-->
    <% params[:start_date].nil? ? month = Date.today.month : month = params[:start_date].to_date.month %>
    <!--only show the dates from the current month on calendar-->
        <% if date.month == month %>
          <%= link_to date.strftime("%d"), new_session_path(section: @section, date: date) %>
        <% end %>
    <% end %>
    </div>
</div>    
    


<br>Enrolled students:
<ul><% @section.students.each do |student|%>
    <li><%= "#{student.first_name} #{student.last_name} "%></li>
    <% end %>
    <%= if @section.students.empty? then "No students currently enrolled" end %>
</ul>
</br>


<%= link_to "Add/remove students in section", edit_section_path(@section) %>