config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :courses
  resources :students
  resources :sections
  resources :sessions

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Home", root_url, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "View courses", courses_path %></li>
                <li><%= link_to "Add a course", new_course_path %></li>
                <li><%= link_to "View students", students_path %></li>
                <li><%= link_to "Add a Student", new_student_path %></li>
                
                <!--<li><%= link_to "Add a student", "#" %></li>-->
                <li><%= link_to "Login", "#" %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= render "layouts/rails_default" %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
  </div>

  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>